### PR TITLE
Module patched with unified new and / or modified icons

### PR DESCRIPTION
**Pull request by Mystery-Man-From-Ouperspace**
Module patched with new and / or modified icons. 3 different icons for the 3 species of birds. Also file fr.json corrected and updated.

### CODE REVIEW

**Comment by ghost91-** [comment]
To be honest, I think the icons look quite a bit more inconsistent now. Some have this "grainy" style, some are simple flat icons. I would prefer to have all of them in the same style. The quality of the ones that you (seem to) have modified to make the background dark also isn't ideal. Possibly, we'd simply need to replace all icons with new ones.

Also, what's the exact licensing on the icons you added? Did you create them yourself, or copy them from somewhere?

**Comment by ghost91-** [comment]
I would prefer for translation changes to be done in a separate PR from the icon changes. Partially, because I'm happy to incorporate the translation changes, but in the current state, it's unlikely the icon changes will be accepted.

**Comment by ghost91-** [comment]
Please make sure the commits adhere to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). I automatically create release notes based on the commits and they need to adhere to this convention for that to work.

Also, please squash them. There should be one commit that changes the translation (preferably in a separate PR), and one commit that adjusts the icons.

**Review by ghost91- — CHANGES_REQUESTED** [review]
Please address the points I mentioned in my other comments.

**Comment by Mystery-Man-From-Ouperspace** [comment]
Hello. All flat icons with provenance in this repertory : [https://github.com/Mystery-Man-From-Ouperspace/fxmaster/tree/main/assets/particle-effects/icons](https://github.com/Mystery-Man-From-Ouperspace/fxmaster/tree/main/assets/particle-effects/icons)

**Comment by ghost91-** [comment]
Sorry, licensing is still unclear to me and unfortunately, I don't have the time to deal with getting the licensing right. So we'll keep things as they are for now.

**Comment by Mystery-Man-From-Ouperspace** [comment]
For your information, Foundry VTT uses icons from https://game-icons.net/

**Comment by ghost91-** [comment]
I'm aware, but thanks.

**Comment by Mystery-Man-From-Ouperspace** [comment]
Well, I won't propose anymore enhancement for your module. So you'll keep things as they are for now, if it is what you really want ;)

Have a nice day. Bye.

**Pull request closed without merging**
